export const beverages = [
  'Beer',
  'Carnation Instant Breakfast',
  'Coffee',
  'Energy drink',
  'Grapefruit juice',
  'Hot chocolate',
  'Instant breakfast',
  'Lassi',
  'Milk',
  'Orange juice',
  'Salep, or saloop',
  'Sarabba',
  'Soy milk',
  'Tea',
  'Tomato juice',
  'Aleberry',
  'Anijsmelk',
  'Apple cider',
  'Asiático',
  'Atole',
  'Bajigur',
  'Bandrek',
  'Blackberry demitasse',
  'Blue Blazer',
  'Bouillon',
  'Butter tea',
  'Caudle',
  'Coffee',
  'Hot egg drinks',
  'Espresso',
  'Hot ginger cordial',
  'Greyana rakiya',
  'Grog',
  'Herbal tea',
  'Hot buttered rum',
  'Hot chocolate',
  'Hot toddy',
  'Irish coffee',
  'Hot lemonade',
  "Job's tears",
  'Malted milk',
  'Mate cocido',
  'Mulled wine',
  'Posset',
  'Postum',
  'Rüdesheimer Kaffee',
  'Sake',
  'Salep',
  'Sassafras tea',
  'Smoking Bishop',
  'Soda',
  'Spiced punch',
  'Tea',
  'Wedang Jahe'
];
